#set_property PACKAGE_PIN G2 [get_ports {RED[0]}]
set_property PACKAGE_PIN F4 [get_ports {RED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLUE[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GREEN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[1]}]
set_property PACKAGE_PIN H2 [get_ports {GREEN[0]}]
set_property PACKAGE_PIN D3 [get_ports {GREEN[1]}]
set_property PACKAGE_PIN F3 [get_ports {BLUE[0]}]
set_property PACKAGE_PIN E3 [get_ports {BLUE[1]}]
set_property PACKAGE_PIN C4 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports LE]
set_property IOSTANDARD LVCMOS33 [get_ports LED_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports OE_N]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property DRIVE 12 [get_ports LE]
set_property DRIVE 12 [get_ports LED_CLK]
set_property DRIVE 12 [get_ports OE_N]
set_property SLEW SLOW [get_ports LE]
set_property SLEW SLOW [get_ports LED_CLK]
set_property SLEW SLOW [get_ports OE_N]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property PACKAGE_PIN J3 [get_ports {A[0]}]
set_property PACKAGE_PIN G1 [get_ports {A[2]}]
set_property PACKAGE_PIN J2 [get_ports {A[1]}]
set_property PACKAGE_PIN H1 [get_ports {A[3]}]
set_property PACKAGE_PIN G2 [get_ports {RED[0]}]
set_property PACKAGE_PIN E1 [get_ports LE]
set_property PACKAGE_PIN D2 [get_ports OE_N]
set_property PACKAGE_PIN F1 [get_ports LED_CLK]


